name: Deploy Lambdas

on:
  push:
    branches:
      - main

jobs:
  deploy-chatbot:
    name: Deploy Chatbot Lambda
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar dependencias Chatbot
        run: |
          cd "lambda chatbot"
          mkdir -p package
          if [ -f requirements.txt ]; then pip install -r requirements.txt -t package/; fi
          cp -r *.py core package/
          cd package && zip -r ../chatbot_lambda.zip .

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Subir Chatbot Lambda
        run: |
          aws lambda update-function-code \
            --function-name AgenteDataBedrock \
            --zip-file fileb://lambda\ chatbot/chatbot_lambda.zip

  deploy-feedback:
    name: Deploy Feedback Lambda
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Empaquetar Feedback Lambda
        run: |
          cd "lambda feedback"
          zip -r feedback_lambda.zip .

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Subir Feedback Lambda
        run: |
          aws lambda update-function-code \
            --function-name LambdaUserFeedback \
            --zip-file fileb://lambda\ feedback/feedback_lambda.zip
  
  deploy-etl:
    name: Deploy etl Lambda
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Empaquetar etl Lambda
        run: |
          cd "lambda etl"
          zip -r etl_lambda.zip .

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Subir etl Lambda
        run: |
          aws lambda update-function-code \
            --function-name LambdaEtlPostgreSql \
            --zip-file fileb://lambda\ etl/etl_lambda.zip

  deploy-orquest:
    name: Deploy orquest Lambda
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Empaquetar orquest Lambda
        run: |
          cd "lambda orquest"
          zip -r orquest_lambda.zip .

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Subir orquest Lambda
        run: |
          aws lambda update-function-code \
            --function-name OrquestLambda \
            --zip-file fileb://lambda\ orquest/orquest_lambda.zip
